export const ROLE_OPTIONS = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Security Engineer",
  "QA Engineer",
  "Product Manager",
  "UI/UX Designer",
] as const;

const SKILLS_BY_ROLE: Record<string, readonly string[]> = {
  "frontend developer": [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Redux",
    "HTML/CSS",
    "Vue.js",
  ],
  "backend developer": [
    "Node.js",
    "Python",
    "Java",
    "Go",
    "PostgreSQL",
    "Redis",
    "REST APIs",
    "GraphQL",
  ],
  "full stack developer": [
    "React",
    "Next.js",
    "Node.js",
    "TypeScript",
    "PostgreSQL",
    "MongoDB",
    "GraphQL",
    "AWS",
  ],
  "mobile developer": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Android",
    "iOS",
    "Firebase",
    "TypeScript",
  ],
  "devops engineer": [
    "Docker",
    "Kubernetes",
    "Terraform",
    "AWS",
    "CI/CD",
    "Linux",
    "Prometheus",
    "GitHub Actions",
  ],
  "site reliability engineer": [
    "Kubernetes",
    "Terraform",
    "AWS",
    "GCP",
    "Observability",
    "Incident Response",
    "Linux",
    "Scripting",
  ],
  "cloud engineer": [
    "AWS",
    "Azure",
    "GCP",
    "Terraform",
    "Kubernetes",
    "Serverless",
    "Cloud Security",
    "Networking",
  ],
  "data engineer": [
    "SQL",
    "Python",
    "Spark",
    "Airflow",
    "dbt",
    "Snowflake",
    "BigQuery",
    "ETL",
  ],
  "data scientist": [
    "Python",
    "SQL",
    "Pandas",
    "Scikit-learn",
    "Statistics",
    "A/B Testing",
    "Visualization",
    "Jupyter",
  ],
  "machine learning engineer": [
    "Python",
    "PyTorch",
    "TensorFlow",
    "MLOps",
    "Feature Engineering",
    "Model Deployment",
    "Docker",
    "Kubernetes",
  ],
  "ai engineer": [
    "Python",
    "LLMs",
    "RAG",
    "Vector Databases",
    "Prompt Engineering",
    "PyTorch",
    "LangChain",
    "FastAPI",
  ],
  "security engineer": [
    "Application Security",
    "Cloud Security",
    "SIEM",
    "Threat Modeling",
    "Penetration Testing",
    "IAM",
    "Network Security",
    "Incident Response",
  ],
  "qa engineer": [
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "Playwright",
    "Cypress",
    "API Testing",
    "Jest",
    "Test Planning",
  ],
  "product manager": [
    "Product Strategy",
    "Roadmapping",
    "User Research",
    "Analytics",
    "A/B Testing",
    "PRDs",
    "Stakeholder Management",
    "Agile",
  ],
  "ui/ux designer": [
    "Figma",
    "Design Systems",
    "Prototyping",
    "User Research",
    "Interaction Design",
    "Wireframing",
    "Visual Design",
    "Accessibility",
  ],
};

const DEFAULT_SKILL_OPTIONS = [
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "AWS",
  "SQL",
  "Docker",
] as const;

export const LOCATION_OPTIONS = [
  "Remote",
  "Hybrid",
  "On-site",
  "Bengaluru, India",
  "Hyderabad, India",
  "Pune, India",
  "Chennai, India",
  "Mumbai, India",
  "Delhi NCR, India",
  "United States",
  "San Francisco Bay Area, USA",
  "New York City, USA",
  "Austin, USA",
  "Seattle, USA",
  "London, UK",
  "Berlin, Germany",
  "Singapore",
  "Dubai, UAE",
] as const;

export function getSkillOptionsForRole(role: string): readonly string[] {
  const normalizedRole = role.trim().toLowerCase();
  if (!normalizedRole) {
    return DEFAULT_SKILL_OPTIONS;
  }

  return SKILLS_BY_ROLE[normalizedRole] ?? DEFAULT_SKILL_OPTIONS;
}
